replace ccode=  2 if code=="USA";
replace ccode= 20 if code=="CAN";
replace ccode= 31 if code=="BHS";
replace ccode= 40 if code=="CUB";
replace ccode= 41 if code=="HTI";
replace ccode= 42 if code=="DOM";
replace ccode= 51 if code=="JAM";
replace ccode= 52 if code=="TTO";
replace ccode= 53 if code=="BRB";
replace ccode= 54 if code=="DMA";
replace ccode= 55 if code=="GRD";
replace ccode= 56 if code=="LCA";
replace ccode= 57 if code=="VCT";
replace ccode= 58 if code=="ATG";
replace ccode= 60 if code=="KNA";
replace ccode= 70 if code=="MEX";
replace ccode= 80 if code=="BLZ";
replace ccode= 90 if code=="GTM";
replace ccode= 91 if code=="HND";
replace ccode= 92 if code=="SLV";
replace ccode= 93 if code=="NIC";
replace ccode= 94 if code=="CRI";
replace ccode= 95 if code=="PAN";
replace ccode=100 if code=="COL";
replace ccode=101 if code=="VEN";
replace ccode=110 if code=="GUY";
replace ccode=115 if code=="SUR";
replace ccode=130 if code=="ECU";
replace ccode=135 if code=="PER";
replace ccode=140 if code=="BRA";
replace ccode=145 if code=="BOL";
replace ccode=150 if code=="PRY";
replace ccode=155 if code=="CHL";
replace ccode=160 if code=="ARG";
replace ccode=165 if code=="URY";
replace ccode=200 if code=="GBR";
replace ccode=205 if code=="IRL";
replace ccode=210 if code=="NLD";
replace ccode=211 if code=="BEL";
replace ccode=212 if code=="LUX";
replace ccode=220 if code=="FRA";
replace ccode=221 if code=="MCO";
replace ccode=223 if code=="LIE";
replace ccode=225 if code=="CHE";
replace ccode=230 if code=="ESP";
replace ccode=232 if code=="AND";
replace ccode=235 if code=="PRT";
replace ccode=255 if code=="DEU";
replace ccode=290 if code=="POL";
replace ccode=305 if code=="AUT";
replace ccode=310 if code=="HUN";
replace ccode=316 if code=="CZE";
replace ccode=317 if code=="SVK";
replace ccode=325 if code=="ITA";
replace ccode=331 if code=="SMR";
replace ccode=338 if code=="MLT";
replace ccode=339 if code=="ALB";
replace ccode=343 if code=="MKD";
replace ccode=344 if code=="HRV";
replace ccode=345 if code=="YUG";
replace ccode=346 if code=="BIH";
replace ccode=349 if code=="SVN";
replace ccode=350 if code=="GRC";
replace ccode=352 if code=="CYP";
replace ccode=355 if code=="BGR";
replace ccode=359 if code=="MDA";
replace ccode=360 if code=="ROU";
replace ccode=365 if code=="RUS";
replace ccode=366 if code=="EST";
replace ccode=367 if code=="LVA";
replace ccode=368 if code=="LTU";
replace ccode=369 if code=="UKR";
replace ccode=370 if code=="BLR";
replace ccode=371 if code=="ARM";
replace ccode=372 if code=="GEO";
replace ccode=373 if code=="AZE";
replace ccode=375 if code=="FIN";
replace ccode=380 if code=="SWE";
replace ccode=385 if code=="NOR";
replace ccode=390 if code=="DNK";
replace ccode=395 if code=="ISL";
replace ccode=402 if code=="CPV";
replace ccode=403 if code=="STP";
replace ccode=404 if code=="GNB";
replace ccode=411 if code=="GNQ";
replace ccode=420 if code=="GMB";
replace ccode=432 if code=="MLI";
replace ccode=433 if code=="SEN";
replace ccode=434 if code=="BEN";
replace ccode=435 if code=="MRT";
replace ccode=436 if code=="NER";
replace ccode=437 if code=="CIV";
replace ccode=438 if code=="GIN";
replace ccode=439 if code=="BFA";
replace ccode=450 if code=="LBR";
replace ccode=451 if code=="SLE";
replace ccode=452 if code=="GHA";
replace ccode=461 if code=="TGO";
replace ccode=471 if code=="CMR";
replace ccode=475 if code=="NGA";
replace ccode=481 if code=="GAB";
replace ccode=482 if code=="CAF";
replace ccode=483 if code=="TCD";
replace ccode=484 if code=="COG";
replace ccode=490 if code=="COD";
replace ccode=500 if code=="UGA";
replace ccode=501 if code=="KEN";
replace ccode=510 if code=="TZA";
replace ccode=516 if code=="BDI";
replace ccode=517 if code=="RWA";
replace ccode=520 if code=="SOM";
replace ccode=522 if code=="DJI";
replace ccode=530 if code=="ETH";
replace ccode=531 if code=="ERI";
replace ccode=540 if code=="AGO";
replace ccode=541 if code=="MOZ";
replace ccode=551 if code=="ZMB";
replace ccode=552 if code=="ZWE";
replace ccode=553 if code=="MWI";
replace ccode=560 if code=="ZAF";
replace ccode=565 if code=="NAM";
replace ccode=570 if code=="LSO";
replace ccode=571 if code=="BWA";
replace ccode=572 if code=="SWZ";
replace ccode=580 if code=="MDG";
replace ccode=581 if code=="COM";
replace ccode=590 if code=="MUS";
replace ccode=591 if code=="SYC";
replace ccode=600 if code=="MAR";
replace ccode=615 if code=="DZA";
replace ccode=616 if code=="TUN";
replace ccode=620 if code=="LBY";
replace ccode=625 if code=="SDN";
replace ccode=630 if code=="IRN";
replace ccode=640 if code=="TUR";
replace ccode=645 if code=="IRQ";
replace ccode=651 if code=="EGY";
replace ccode=652 if code=="SYR";
replace ccode=660 if code=="LBN";
replace ccode=663 if code=="JOR";
replace ccode=666 if code=="ISR";
replace ccode=670 if code=="SAU";
replace ccode=679 if code=="YEM";
replace ccode=690 if code=="KWT";
replace ccode=692 if code=="BHR";
replace ccode=694 if code=="QAT";
replace ccode=696 if code=="ARE";
replace ccode=698 if code=="OMN";
replace ccode=700 if code=="AFG";
replace ccode=701 if code=="TKM";
replace ccode=702 if code=="TJK";
replace ccode=703 if code=="KGZ";
replace ccode=704 if code=="UZB";
replace ccode=705 if code=="KAZ";
replace ccode=710 if code=="CHN";
replace ccode=712 if code=="MNG";
replace ccode=713 if code=="TWN";
replace ccode=731 if code=="PRK";
replace ccode=732 if code=="KOR";
replace ccode=740 if code=="JPN";
replace ccode=750 if code=="IND";
replace ccode=760 if code=="BTN";
replace ccode=770 if code=="PAK";
replace ccode=771 if code=="BGD";
replace ccode=775 if code=="MMR";
replace ccode=780 if code=="LKA";
replace ccode=781 if code=="MDV";
replace ccode=790 if code=="NPL";
replace ccode=800 if code=="THA";
replace ccode=811 if code=="KHM";
replace ccode=812 if code=="LAO";
replace ccode=816 if code=="VNM";
replace ccode=820 if code=="MYS";
replace ccode=830 if code=="SGP";
replace ccode=835 if code=="BRN";
replace ccode=840 if code=="PHL";
replace ccode=850 if code=="IDN";
replace ccode=860 if code=="TLS";
replace ccode=900 if code=="AUS";
replace ccode=910 if code=="PNG";
replace ccode=920 if code=="NZL";
replace ccode=935 if code=="VUT";
replace ccode=940 if code=="SLB";
replace ccode=946 if code=="KIR";
replace ccode=947 if code=="TUV";
replace ccode=950 if code=="FJI";
replace ccode=955 if code=="TON";
replace ccode=970 if code=="NRU";
replace ccode=983 if code=="MHL";
replace ccode=986 if code=="PLW";
replace ccode=987 if code=="FSM";
replace ccode=990 if code=="WSM";
replace ccode=490 if code=="ZAR";